baseURL: "https://supolka.com/"
languageCode: "ru_BY"
title: "Pirs"

theme: "hyde"

params:
  description: "Сообщество Пирс"
  themeColor: "theme-base-0d"
  copyright: " "
  layoutReverse: false

markup:
  goldmark:
    renderer:
      unsafe: true

menus:
  main:
    - name: "Slack"
      url: "https://pirsby.slack.com"
      weight: 1000
    - name: "Telegram"
      url: "https://t.me/pirsinfo"
      weight: 1001
    - name: "Contribute"
      url: "https://github.com/IRus/OpenPirs"
      weight: 1002
